### ISSUE TITLE
Code Lou Track to be Completed

### ISSUE THREAD

**Issue by themelissaellis** [themelissaellis/Treehouse#2]
## TODO

*Courses left to complete the CodeLou Track:*

- [ ] Debugging CSS with Chrome Dev Tools
 - [ ] CSS Flexbox Layout
- [ ] HTML Forms
- [ ] JavaScript Numbers
- [ ] JavaScript Functions
- [ ] JavaScript Loops
- [ ] JavaScript Arrays
- [ ] JavaScript Objects
- [ ] CSS Selectors
- [ ] Web Accessibility Compliance
- [ ] Website Optimization

🍾 😸
